name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Surge
      run: npm install --global surge

    - name: Deploy to Surge
      env:
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        SURGE_DOMAIN: 2023-1009.surge.sh
      run: surge --project ./ --domain $SURGE_DOMAIN --token $SURGE_TOKEN
